#!/bin/env python

import subprocess
import csv
from repeater import SamplesPool
from datetime import datetime, timedelta, time
from glob import glob
import click
import os
import shutil
from collections import OrderedDict
from indexed import IndexedOrderedDict
import itertools
from random import randrange

CONTEXTS = IndexedOrderedDict()
CONTEXTS['morning'] = {'exe': 'blender/morning.blend',
                         'start_dt': datetime.strptime("2016-02-01 08:00:00", "%Y-%m-%d %H:%M:%S")}
CONTEXTS['evening'] = {'exe': 'blender/evening.blend',
                         'start_dt': datetime.strptime("2016-02-01 18:00:00", "%Y-%m-%d %H:%M:%S")}

def validate_dt(value):
    try:
        dt = datetime.strptime(value, "%Y-%m-%d %H:%M:%S")
        return dt
    except ValueError:
        raise click.BadParameter("Please enter a valid datetime")

def validate_date(value):
    try:
        dt = datetime.strptime(value, "%Y-%m-%d")
        return dt
    except ValueError:
        raise click.BadParameter("Please enter a valid date")

@click.group()
def main():
    """OpenSHS: Open Smart Home Simulator"""
    pass

@main.command()
@click.option('--list-contexts', '-lc', default=False, is_flag=True, help='Lists the available contexts.')
@click.option('--recorded-samples', '-rs', default=False, is_flag=True, help='Shows the status of the recorded contexts samples.')
def status(list_contexts, recorded_samples):
    """Shows the current status of the experiment."""
    if list_contexts:
        click.echo(", ".join([x for x in CONTEXTS.keys()]))

    if recorded_samples:
        for context in CONTEXTS:
            files = glob('temp/*_' + context + '_*.csv')
            click.echo("For context " + click.style(context, bold=True) + ": " + str(len(files)) + " Samples.")

@main.command()
@click.option('--context', '-c', type=click.Choice(list(CONTEXTS.keys())), help='Which context to start.')
@click.option('--primusrun', '-p', default=False, is_flag=True, help='Start the context with primus support (Linux Only).')
def start(context, primusrun):
    """Start a context experiment."""
    click.echo('Starting the ' + click.style(context, bold=True) + ' context.')
    start_dt = click.prompt("What's the starting time?",
                            default=CONTEXTS[context]['start_dt'],
                            value_proc=validate_dt)
    CONTEXTS[context]['start_dt'] = start_dt

    # Write the starting datetime for blender to read
    sf = open('blender/start_time.txt', 'w')
    sf.write(str(int(start_dt.timestamp())))
    sf.close()

    weekday_p = is_weekday(start_dt)

    if primusrun:
        subprocess.call(["primusrun", "blender", CONTEXTS[context]['exe']], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    else:
        subprocess.call(["blender", CONTEXTS[context]['exe']], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    os.rename('temp/output.csv', 'temp/' + ('weekday_' if weekday_p else 'weekend_') + context + '_' + datetime.strftime(start_dt, "%Y-%m-%d %H:%M:%S") + '.csv')

@main.command()
@click.option('--days', '-d', type=int, default=30, help='How many days to generate.', )
@click.option('--start-date', '-sd', type=validate_date, help='The starting date for the aggregated dataset.')
def aggregate(days, start_date):
    """Aggregate the datasets."""

    files = glob('temp/*.csv')

    aday = timedelta(days=1)
    dt = start_date

    # The header row
    with open(files[0], 'r') as headfile:
        csv_reader = csv.reader(headfile)
        header = next(csv_reader)
    header.append('timestamp')

    d_rows = []
    with open('datasets/dataset.csv', 'w') as outf:
        csv_writer = csv.writer(outf)
        csv_writer.writerow(header)

        for _ in range(days):
            if is_weekday(dt):
                for context in CONTEXTS:
                    pool_files = glob('temp/weekday_' + context + '*.csv')
                    pool = SamplesPool(pool_files)
                    rep_rows = pool.generate_sample(header=False)
                    d_rows += add_timestamp_field(rep_rows, random_timestamp(dt, pool_files))
            else:
                for context in CONTEXTS:
                    pool_files = glob('temp/weekend_' + context + '*.csv')
                    pool = SamplesPool(pool_files)
                    rep_rows = pool.generate_sample(header=False)
                    d_rows += add_timestamp_field(rep_rows, random_timestamp(dt, pool_files))
            dt += aday

        csv_writer.writerows(d_rows)

def random_timestamp(dt, pool_files):
    pool_times = [x[x.find(' ')+1:-4] for x in pool_files]
    times = [datetime.strptime(x, "%H:%M:%S") for x in pool_times]
    rand_date = random_date(min(times), max(times))
    new_dt = datetime(dt.year, dt.month, dt.day, rand_date.hour, rand_date.minute, rand_date.second)
    return new_dt

def random_date(start, end):
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + timedelta(seconds=random_second)

def add_timestamp_field(reader, start_dt):
    if type(start_dt) is str:
        start_dt = datetime.strptime(start_dt, "%Y-%m-%d %H:%M:%S")
    ts = start_dt
    asec = timedelta(seconds=1)
    result = []

    for i in reader:
        row = i + [ts.strftime("%Y-%m-%d %H:%M:%S")]
        result.append(row)
        ts += asec
    return result

def is_weekday(dt):
    if dt.weekday() < 5:
        return True
    else:
        return False


if __name__ == '__main__':
    main()
